### ISSUE TITLE
Working folder

### ISSUE THREAD

**Issue by deka** [lemoinek/TFS.Extension.CleanupFolder#2]

**Comment by deka** [comment]
Perhaps not util with credentials...
Something like "\\SERVERXXX\c$\programmes files/zz/xx" can work...

**Comment by lemoinek** [comment]
This seems a good idea
How urgent do you need this feature?

**Comment by deka** [comment]
Done : https://marketplace.visualstudio.com/items?itemName=deka.remote-retention-cleaner

**Comment by lemoinek** [comment]
i had the same thing already prepared :(
